### ISSUE TITLE
Does not work with Java 8?

### ISSUE THREAD

**Issue by markus-s24** [bsideup/redis-maven-plugin#5]
Jul 22, 2015 11:01:29 AM io.netty.util.internal.PlatformDependent hasJavassist0
INFORMATION: You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
java.lang.ClassNotFoundException: java.util.HashMap$Entry
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at redis.server.netty.SimpleRedisServer.<clinit>(SimpleRedisServer.java:270)
        at ru.trylogic.maven.plugins.redis.RunRedisMojo.doExecute(RunRedisMojo.java:47)
        at ru.trylogic.maven.plugins.redis.RunRedisMojo.execute(RunRedisMojo.java:43)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by cescoffier** [comment]
There is an easy work around:

``` xml
<plugin>
  <groupId>ru.trylogic.maven.plugins</groupId>
  <artifactId>redis-maven-plugin</artifactId>
  <version>1.4.6</version>
  <configuration>
    <forked>true</forked>
  </configuration>
  <executions>
    <execution>
      <id>start-redis</id>
      <phase>pre-integration-test</phase>
      <goals>
        <goal>run</goal>
      </goals>
    </execution>
    <execution>
      <id>stop-redis</id>
      <phase>post-integration-test</phase>
      <goals>
        <goal>shutdown</goal>
      </goals>
    </execution>
  </executions>
  <!-- Add javassist to the plugin classpath -->
  <dependencies>
    <dependency>
      <groupId>org.javassist</groupId>
      <artifactId>javassist</artifactId>
      <version>3.19.0-GA</version>
    </dependency>
  </dependencies>
</plugin>
```

**Comment by markus-s24** [comment]
That does not work. The root cause for the problem is, that with java 8 the inner class Entry of HashMap does not exist anymore. That is a problem of the Redis implementation used by this plugin, so I have to create an issue there.

**Comment by cescoffier** [comment]
You are right, I still have the stack trace.
However with the javassist dependency it starts.

**Comment by markus-s24** [comment]
The plugin works for me even without the dependency. I am just annoyed about the exception in the build log.

**Comment by danielfc** [comment]
The plugin works for me as well, but it keeps logging warnings after shutting down Redis. Have you seen this one?

``` txt
Tests run: 33, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- redis-maven-plugin:1.4.6:shutdown (stop-redis) @ be-entitlements ---
[INFO] Shutting down Redis server...
Sep 28, 2015 11:30:27 AM io.netty.channel.DefaultChannelPipeline$TailHandler exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:259)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:885)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:226)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:70)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:429)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:392)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:322)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:114)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by jhovell** [comment]
@danielfc I get the same shutdown warning in the maven log, probably repeated 100+ times, filling my logs. What's worse amazingly it doesn't seem possible to configure logging in the POM with maven to suppress certain warnings so I guess I am stuck with this for now. I found this Netty bug report, maybe a newer version of Netty might resolve the issue, but I haven't tried that https://github.com/netty/netty/issues/2596

The hashmap entry warning is also annoying to not be able to resolve but at least for now it is 100x less of an issue in the build log :)

Other that those issues, the plugin is great!

**Comment by jaceko** [comment]
Any plans to fix that?

**Comment by bsideup** [comment]
@jaceko I'm actually surprised that people still use the plugin :D 

In the era of Docker, I highly recommend taking a look at another project I participate now, http://testcontainers.org
it's way more powerful approach to run the dependencies for your tests :)

**Comment by jaceko** [comment]
Thanks. Sometimes the simplest things work the best, especially for smaller projects with few external dependencies. In my case maven plugins work perfect and I want to keep it simple. it's just this annoying stacktrace. If I provide the fix would you make a release of the plugin?

**Comment by bsideup** [comment]
@jaceko if I restore my Maven Central credentials :D But anyway, PR will be highly appreciated, I will find a way to release it :)

**Comment by russoz** [comment]
@bsideup hope you do find them :-) just found this plugin and it's exactly what I need.

**Comment by urvanov-ru** [comment]
@bsideup , I need this plugin on Java 8 too! Please!

**Comment by dpfundt** [comment]
How did we go guys? Any update to this to fix the stacktrace in logs for Java 8?

**Comment by urvanov-ru** [comment]
Maybe someone would be brave enough to make a fork or pull request...
